apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-checkuptime
  namespace: mcp
  labels:
    app.kubernetes.io/name: mcp-checkuptime
    app.kubernetes.io/instance: mcp-checkuptime
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/component: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp-checkuptime
      app.kubernetes.io/instance: mcp-checkuptime
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mcp-checkuptime
        app.kubernetes.io/instance: mcp-checkuptime
        app.kubernetes.io/version: "2.0.1"
    spec:
      containers:
        - name: mcp-server
          image: zcr.zephryn.io/mcp-checkuptime:2.0.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          env:
            - name: MCP_HOST
              value: "0.0.0.0"
            - name: MCP_PORT
              value: "9000"
            - name: MCP_TRANSPORT
              value: "streamable_http"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mcp-bearer-token
                  key: token
                  optional: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 1000
